// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-zpm8V-z9x_-YZm3lB65FOLGMZwoRjx4',
    appId: '1:309504893881:web:952c6cefe5624683440c68',
    messagingSenderId: '309504893881',
    projectId: 'fir-test-9f3d7',
    authDomain: 'fir-test-9f3d7.firebaseapp.com',
    databaseURL: 'https://fir-test-9f3d7.firebaseio.com',
    storageBucket: 'fir-test-9f3d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6-yNiMuN5kPjnl4jkJDGnj-EhnAPHmo',
    appId: '1:309504893881:android:1e1a835e15987d2e440c68',
    messagingSenderId: '309504893881',
    projectId: 'fir-test-9f3d7',
    databaseURL: 'https://fir-test-9f3d7.firebaseio.com',
    storageBucket: 'fir-test-9f3d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo8NzUYnU6ogDod-MOcrqxLc8t6vyy4lA',
    appId: '1:309504893881:ios:4418fe305b92c3f9440c68',
    messagingSenderId: '309504893881',
    projectId: 'fir-test-9f3d7',
    databaseURL: 'https://fir-test-9f3d7.firebaseio.com',
    storageBucket: 'fir-test-9f3d7.appspot.com',
    androidClientId: '309504893881-hrk1bv648g3d3u5jpn6pjvk4babhhqfc.apps.googleusercontent.com',
    iosClientId: '309504893881-2b5idbnuut9htoidbpq1vmrkb2llhdnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bank.application.contasBancarias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo8NzUYnU6ogDod-MOcrqxLc8t6vyy4lA',
    appId: '1:309504893881:ios:4418fe305b92c3f9440c68',
    messagingSenderId: '309504893881',
    projectId: 'fir-test-9f3d7',
    databaseURL: 'https://fir-test-9f3d7.firebaseio.com',
    storageBucket: 'fir-test-9f3d7.appspot.com',
    androidClientId: '309504893881-hrk1bv648g3d3u5jpn6pjvk4babhhqfc.apps.googleusercontent.com',
    iosClientId: '309504893881-2b5idbnuut9htoidbpq1vmrkb2llhdnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bank.application.contasBancarias',
  );
}
